apiVersion: apps/v1
kind: Deployment
metadata:
  name: producservice-v1
spec:
  replicas: 2
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: producservice-v1
  template:
    metadata:
      labels:
        app: producservice-v1
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        name: producservice-v1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: producservice-v1-config