name: Despliegue app in argon
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    name: Build imagen docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Codigo correcto

      - uses: docker/login-action@v3
        name: Login docker hub 
        with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - name: Get date and build number
        run: |
          BUILD_DATE=$(date +'%Y%m%d')
          BUILD_NUMBER=${{ github.run_number }}
          IMAGE_TAG="${BUILD_DATE}-${BUILD_NUMBER}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "${IMAGE_TAG}" > image_tag.txt
      
      - uses: actions/upload-artifact@v3
        name: Upload IMAGE_TAG artifact
        with:
          name: image_tag
          path: image_tag.txt

      
      - uses: docker/build-push-action@v6
        name: buil and push 
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:${{ env.IMAGE_TAG }}, ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
     
  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        name: Download IMAGE_TAG artifact
        with:
          name: image_tag

      - name: Read IMAGE_TAG from file
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=${IMAGE_TAG}"
      
      - name: Update Image Tag Values
        run: |
          chart_dir="deploy"
          new_image_tag=$(cat image_tag.txt)
          # Verificar si el tag no está vacío
          if [ -z "$new_image_tag" ]; then
          echo "Error: El tag de la imagen está vacío."
          exit 1
          fi
          # Update the values.yaml file with the new image tag
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

    
        
      - name: Commit the changes made
        run: | 
         git config --global user.name 'javier '
         git config --global user.email 'wviracoc@bancolombia.com.co'
         git status
         git commit -am "updating image tag"
         git push