name: Despliegue app in argon
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    name: Build imagen docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Codigo correcto

      - uses: docker/login-action@v3
        name: Login docker hub 
        with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - name: Get date and build number
        run: echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
      
      - uses: docker/build-push-action@v6
        name: buil and push 
        with:
          push: true
          tags: rinkiyakedad/go-server:${{ env.BUILD_DATE }}-${{ env.BUILD_NUMBER }}, rinkiyakedad/go-server:latest
