name: Despliegue app in argon
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    name: Build imagen docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Codigo correcto

      - uses: docker/login-action@v3
        name: Login docker hub 
        with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - name: Get date and build number
        run: |
          BUILD_DATE=$(date +'%Y%m%d')
          BUILD_NUMBER=${{ github.run_number }}
          echo "IMAGE_TAG=${BUILD_DATE}-${BUILD_NUMBER}" >> $GITHUB_ENV
      
      - uses: docker/build-push-action@v6
        name: buil and push 
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-service:${{ env.IMAGE_TAG }}, ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2


      - name: Update Image Tag Values
        run: |
          chart_dir="deploy"
          new_image_tag="${{ env.IMAGE_TAG }}"

          # Update the values.yaml file with the new image tag
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
    
      - name: Commit the changes made
        run: | 
         git config --global user.name 'javierWill08'
         git config --global user.email 'javier_12-9will@hotmail.com'
         git commit -am "updating image tag"
         git push